# Generated by Django 4.2.3 on 2023-07-27 06:01

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ('app_advertisements', '0001_initial'),
        # Замените '000x_previous_migration' на номер предыдущей миграции
    ]

    operations = [
        migrations.AlterModelTable('advertisement', 'advertisements'), # Замените 'advertisements' на новое имя таблицы
    ]
